# Generated by Django 3.1.2 on 2020-12-31 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('medios_off_line', 'medios_off_line'), ('medios_en_tienda', 'medios_en_tienda'), ('e-marketing', 'e-marketing'), ('relaciones_publicas', 'relaciones_publicas'), ('mercadotecnia', 'mercadotecnia'), ('medicion_digital', 'medicion_digital'), ('mkt_digital', 'mkt_digital')], default=None, max_length=25, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
