# Generated by Django 3.1.2 on 2021-01-06 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=25)),
                ('usuario_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Esfuerzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_macro', models.CharField(max_length=60)),
                ('segmento', models.CharField(max_length=60)),
                ('canal', models.CharField(max_length=60)),
                ('subcanal', models.CharField(max_length=60)),
                ('inicio', models.DateField(null=True, verbose_name='Fecha de inicio de la campaña')),
                ('fin', models.DateField(null=True, verbose_name='Fecha de fin de la campaña')),
                ('gasto', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estatus', models.CharField(max_length=2)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.campania')),
                ('usuario_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
