# Generated by Django 3.1.2 on 2021-01-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esfuerzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_macro', models.TextField(max_length=60)),
                ('segmento', models.TextField(max_length=60)),
                ('canal', models.TextField(max_length=60)),
                ('subnanal', models.TextField(max_length=60)),
                ('inicio', models.DateTimeField(verbose_name='Fecha de inicio de la campaña')),
                ('fin', models.DateTimeField(verbose_name='Fecha de fin de la campaña')),
                ('gasto', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estatus', models.TextField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(blank=True, choices=[('medios_off_line', 'medios_off_line'), ('medios_en_tienda', 'medios_en_tienda'), ('e-marketing', 'e-marketing'), ('relaciones_publicas', 'relaciones_publicas'), ('mercadotecnia', 'mercadotecnia'), ('medicion_digital', 'medicion_digital'), ('mkt_digital', 'mkt_digital')], default=None, max_length=25, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campanias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.esfuerzo')),
                ('usuario_creo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
