# Generated by Django 3.1.2 on 2021-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanias',
            name='area',
            field=models.TextField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
