# Generated by Django 3.1.2 on 2021-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MKTOffLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaña', models.CharField(max_length=60)),
                ('objetivo_de_negocio', models.CharField(max_length=60)),
                ('unidad_de_negocio', models.CharField(max_length=60)),
                ('segmento', models.CharField(max_length=60)),
                ('canal', models.CharField(max_length=60)),
                ('subnanal', models.CharField(max_length=60)),
                ('inicio', models.DateTimeField(verbose_name='Fecha de inicio de la campaña')),
                ('fin', models.DateTimeField(verbose_name='Fecha de fin de la campaña')),
                ('gasto', models.FloatField()),
            ],
        ),
    ]
