# Generated by Django 3.1.2 on 2021-01-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_campanias_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esfuerzo',
            name='fin',
            field=models.DateTimeField(null=True, verbose_name='Fecha de fin de la campaña'),
        ),
        migrations.AlterField(
            model_name='esfuerzo',
            name='inicio',
            field=models.DateTimeField(null=True, verbose_name='Fecha de inicio de la campaña'),
        ),
    ]
