# Generated by Django 3.1.2 on 2021-01-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mktoffline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mktoffline',
            old_name='objetivo_de_negocio',
            new_name='objetivo_macro',
        ),
    ]
