# Generated by Django 3.1.2 on 2021-01-01 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210101_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='mktoffline',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mktoffline',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
