# Generated by Django 3.1.2 on 2021-01-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210101_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mktoffline',
            name='unidad_de_negocio',
        ),
    ]
