# Generated by Django 3.1.2 on 2021-01-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210105_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esfuerzo',
            old_name='subnanal',
            new_name='subcanal',
        ),
    ]
