# Generated by Django 3.1.2 on 2021-01-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210105_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esfuerzo',
            old_name='campania_id',
            new_name='campania',
        ),
    ]
